import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { CATEGORIES, RATINGS, daysUntil, todayISO, money, calc, budgetState, byCategory, trend7 } from '../src/utils.js';
assert.ok(CATEGORIES.includes('餐饮'));
assert.ok(RATINGS.includes('后悔'));
assert.equal(daysUntil(new Date(2026,5,30), new Date(2026,4,24)), 37);
assert.equal(todayISO(new Date('2026-05-24T12:00:00')), '2026-05-24');
assert.ok(money(1.5).includes('1.5'));
const entries=[{type:'income',amount:100,account_id:'a',entry_date:'2026-05-24'},{type:'expense',amount:10,category:'餐饮',account_id:'a',entry_date:todayISO()}];
const accounts=[{id:'a',name:'微信',opening_balance:20}];
const out=calc(entries,accounts,[]);
assert.equal(out.stats.income,100);
assert.equal(out.stats.expense,10);
assert.equal(out.accounts[0].balance,110);
assert.equal(byCategory(entries)[0].name,'餐饮');
assert.equal(trend7(entries).length,7);
assert.equal(budgetState({monthlyBudget:100,alertPercent:80},90).status,'warn');
const main=await readFile(new URL('../src/main.js', import.meta.url),'utf8');
const css=await readFile(new URL('../src/styles.css', import.meta.url),'utf8');
const db=await readFile(new URL('../node-functions/_lib/db.js', import.meta.url),'utf8');
assert.ok(!main.includes('import "./styles.css"'));
assert.match(main,/ENTRY_COLLAPSE_LIMIT=8/);
assert.match(main,/toggleEntries/);
assert.match(main,/已自动折叠/);
assert.match(css,/\.listHead\{/);
assert.match(css,/align-items:flex-start/);
assert.match(css,/\.icon\{width:1\.25rem;height:1\.25rem\}/);
assert.match(db,/ledger_tags/);
assert.match(db,/ledger_accounts/);
assert.match(db,/ledger_recurring_bills/);
console.log('All tests passed.');
