import{CATEGORIES,RATINGS,EXAM_DATE,money,todayISO,daysUntil,html,calc,budgetState,byCategory,trend7}from'./utils.js';
const $=s=>document.querySelector(s);let state={entries:[],accounts:[],tags:[],settings:{monthlyBudget:0,alertPercent:80,lowBalanceThreshold:0},transfers:[],recurring:[]};let undo=null;
async function api(path,opt){const r=await fetch(path,{headers:{'content-type':'application/json'},...opt});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'API failed');return j}
async function load(){try{state=await api('/api/state');render('数据库已连接')}catch(e){render('数据库 API 连接失败：'+e.message,true)}}
function options(items,val='id',name='name',sel=''){return items.map(x=>`<option value="${x[val]}" ${x[val]===sel?'selected':''}>${html(x[name])}</option>`).join('')}
function render(msg='',err=false){const {stats,accounts}=calc(state.entries,state.accounts,state.transfers);state.accounts=accounts;const b=budgetState(state.settings,stats.monthExpense);const cats=byCategory(state.entries);const tr=trend7(state.entries);$('#app').innerHTML=`<main class="wrap grid"><section class="card header"><div class="hero"><h1>Yaoxi Ledger</h1><p>单人账本 · EdgeOne Node Function · DATABASE_URL 直连 PostgreSQL</p></div><div class="topcards"><div class="card mini"><span>中考倒计时</span><b>D-${daysUntil(EXAM_DATE)}</b></div><div class="card mini"><span>记录数</span><b>${state.entries.length}</b></div><button class="card mini btn2" id="exportBtn">导出</button></div></section><section class="card status"><div><b class="${err?'bad':'ok'}">${html(msg||'就绪')}</b><div class="muted">本月预算 ${money(state.settings.monthlyBudget)} · 使用率 ${b.used}% · 今日建议 ${money(b.daily)}</div></div><button class="btn2" id="reload">重新读取</button></section><section class="grid g4"><div class="card metric"><span>当前余额</span><strong>${money(stats.balance)}</strong><small class="muted">收入 - 支出</small></div><div class="card metric"><span>本月支出</span><strong>${money(stats.monthExpense)}</strong><small class="${b.status==='danger'?'bad':b.status==='warn'?'warn':'muted'}">预算剩余 ${money(b.left)}</small></div><div class="card metric"><span>今日支出</span><strong>${money(stats.todayExpense)}</strong><small class="muted">今日可用 ${money(b.daily)}</small></div><div class="card metric"><span>最大单笔</span><strong>${money(stats.biggest)}</strong><small class="muted">消费峰值</small></div></section><section class="grid g2"><div class="grid">${entryForm()}${transferForm()}${settingsForm()}${tagBox()}${accountBox()}</div><div class="grid">${trendBox(tr)}${listBox()}${recurringBox()}${categoryBox(cats)}${importBox()}</div></section></main>`;bind()}
function entryForm(){return `<section class="card panel"><h2>快速记一笔</h2><p class="muted">账户、标签、评价均来自数据库。</p><form id="entryForm"><div class="tabs"><button type="button" data-type="expense" class="active">支出</button><button type="button" data-type="income">收入</button><button type="button" data-type="expense">预支</button></div><input name="type" type="hidden" value="expense"><input name="title" placeholder="标题，例如：午饭 / 零花钱" required><div class="formgrid"><input name="amount" type="number" step="0.01" min="0" placeholder="金额" required><select name="account_id" required>${options(state.accounts)}</select><select name="category">${CATEGORIES.map(x=>`<option>${x}</option>`).join('')}</select><select name="rating">${RATINGS.map(x=>`<option>${x}</option>`).join('')}</select></div><input name="entry_date" type="date" value="${todayISO()}"><select name="tag_ids" multiple size="4">${options(state.tags)}</select><textarea name="note" placeholder="备注"></textarea><button class="btn">写入账本</button></form></section>`}
function transferForm(){return `<section class="card panel"><h2>账户转账</h2><form id="transferForm" class="grid"><div class="formgrid"><select name="from_account_id">${options(state.accounts)}</select><select name="to_account_id">${options(state.accounts)}</select></div><input name="amount" type="number" step="0.01" min="0" placeholder="金额" required><input name="transfer_date" type="date" value="${todayISO()}"><input name="note" placeholder="备注"><button class="btn">记录转账</button></form></section>`}
function settingsForm(){const s=state.settings;return `<section class="card panel"><h2>预算阈值</h2><form id="settingsForm" class="formgrid"><input name="monthlyBudget" type="number" value="${s.monthlyBudget||0}" placeholder="本月预算"><input name="alertPercent" type="number" value="${s.alertPercent||80}" placeholder="预警比例"><input name="lowBalanceThreshold" type="number" value="${s.lowBalanceThreshold||0}" placeholder="低余额阈值"><button class="btn">保存阈值</button></form></section>`}
function tagBox(){return `<section class="card panel"><h2>标签</h2><form id="tagForm" class="formgrid"><input name="name" placeholder="新标签"><input name="color" value="#67e8f9"><button class="btn">新增</button></form><div>${state.tags.map(t=>`<span class="tag" style="color:${t.color}">${html(t.name)} <button class="btn2" data-del-tag="${t.id}">×</button></span>`).join('')}</div></section>`}
function accountBox(){return `<section class="card panel"><h2>账户资产</h2><form id="accountForm" class="formgrid"><input name="name" placeholder="账户名"><input name="opening_balance" type="number" step="0.01" placeholder="初始余额"><button class="btn">新增账户</button></form><div class="list">${state.accounts.map(a=>`<div class="item"><div><b>${html(a.name)}</b><div class="muted">初始 ${money(a.opening_balance)}</div></div><b>${money(a.balance)}</b></div>`).join('')}</div></section>`}
function trendBox(tr){const max=Math.max(1,...tr.map(x=>x.expense));return `<section class="card panel"><h2>近 7 日支出趋势</h2><div class="trend">${tr.map(x=>`<div class="col"><i style="height:${Math.max(8,x.expense/max*100)}%"></i><small>${x.key}</small></div>`).join('')}</div></section>`}
function listBox(){return `<section class="card panel"><h2>流水记录</h2><input id="q" placeholder="搜索标题 / 分类 / 备注"><div class="list" id="entryList">${state.entries.map(row).join('')}</div></section>`}
function row(e){return `<article class="item" data-text="${html(`${e.title} ${e.category} ${e.note}`)}"><div><b>${html(e.title)}</b><div class="muted">${e.entry_date} · ${html(e.account_name||'无账户')} · ${html(e.category)} · ${html(e.rating||'')}</div><div>${(e.tags||[]).map(t=>`<span class="tag">${html(t.name)}</span>`).join('')}</div></div><div><b class="${e.type==='income'?'ok':'bad'}">${e.type==='income'?'+':'-'}${money(e.amount)}</b><br><button class="btn2 danger" data-del-entry="${e.id}">删除</button></div></article>`}
function recurringBox(){return `<section class="card panel"><h2>固定支出 / 周期账单</h2><form id="recurringForm" class="grid"><input name="title" placeholder="标题"><div class="formgrid"><select name="type"><option value="expense">支出</option><option value="income">收入</option></select><input name="amount" type="number" step="0.01" placeholder="金额"><select name="account_id">${options(state.accounts)}</select><select name="interval_kind"><option value="daily">每天</option><option value="weekly">每周</option><option value="monthly">每月</option></select></div><input name="category" value="日用"><input name="next_date" type="date" value="${todayISO()}"><button class="btn">新增周期账单</button></form><div class="list">${state.recurring.map(r=>`<div class="item"><span>${html(r.title)} · ${money(r.amount)} · ${r.next_date}</span><span><button class="btn2" data-run-recurring="${r.id}">执行</button><button class="btn2 danger" data-del-recurring="${r.id}">删</button></span></div>`).join('')}</div></section>`}
function categoryBox(cats){const max=Math.max(1,...cats.map(x=>x.value));return `<section class="card panel"><h2>分类支出排行</h2>${cats.map(c=>`<p>${html(c.name)} <span class="muted">${money(c.value)}</span></p><div class="bar"><span style="width:${c.value/max*100}%"></span></div>`).join('')}</section>`}
function importBox(){return `<section class="card panel"><h2>导入 JSON</h2><input type="file" id="importFile" accept="application/json"><p class="muted">支持导入 entries 数组。</p></section>`}
function formData(f){return Object.fromEntries(new FormData(f).entries())}
function bind(){$('#reload').onclick=load;$('#exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='rmb-ledger.json';a.click()};document.querySelectorAll('#entryForm .tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#entryForm .tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#entryForm [name=type]').value=b.dataset.type});$('#entryForm').onsubmit=async e=>{e.preventDefault();const d=formData(e.target);d.tag_ids=[...e.target.tag_ids.selectedOptions].map(o=>o.value);await api('/api/entries',{method:'POST',body:JSON.stringify(d)});load()};$('#transferForm').onsubmit=async e=>{e.preventDefault();await api('/api/transfers',{method:'POST',body:JSON.stringify(formData(e.target))});load()};$('#settingsForm').onsubmit=async e=>{e.preventDefault();await api('/api/settings',{method:'POST',body:JSON.stringify(formData(e.target))});load()};$('#tagForm').onsubmit=async e=>{e.preventDefault();await api('/api/tags',{method:'POST',body:JSON.stringify(formData(e.target))});load()};$('#accountForm').onsubmit=async e=>{e.preventDefault();await api('/api/accounts',{method:'POST',body:JSON.stringify(formData(e.target))});load()};$('#recurringForm').onsubmit=async e=>{e.preventDefault();await api('/api/recurring',{method:'POST',body:JSON.stringify(formData(e.target))});load()};document.body.onclick=async e=>{const t=e.target;if(t.dataset.delEntry){if(!confirm('确认删除？'))return;const old=state.entries.find(x=>x.id===t.dataset.delEntry);await api('/api/entries?id='+t.dataset.delEntry,{method:'DELETE'});undo=old;load();setTimeout(()=>undo=null,5000)}if(t.dataset.delTag){await api('/api/tags?id='+t.dataset.delTag,{method:'DELETE'});load()}if(t.dataset.runRecurring){await api('/api/recurring?action=run&id='+t.dataset.runRecurring,{method:'POST'});load()}if(t.dataset.delRecurring){await api('/api/recurring?id='+t.dataset.delRecurring,{method:'DELETE'});load()}};$('#q').oninput=e=>document.querySelectorAll('#entryList .item').forEach(x=>x.style.display=x.dataset.text.includes(e.target.value)?'flex':'none');$('#importFile').onchange=async e=>{const f=e.target.files[0];if(f){await api('/api/import',{method:'POST',body:await f.text()});load()}}}
load();
