export const CATEGORIES=['餐饮','交通','学习','数码','社交','日用','收入','其他'];
export const RATINGS=['必要','可接受','浪费','后悔'];
export const EXAM_DATE=new Date(2026,5,30);
export function money(v){return new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY',maximumFractionDigits:2}).format(Number(v||0));}
export function todayISO(d=new Date()){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
export function daysUntil(t,from=new Date()){const a=new Date(from.getFullYear(),from.getMonth(),from.getDate());const b=new Date(t.getFullYear(),t.getMonth(),t.getDate());return Math.max(Math.ceil((b-a)/86400000),0)}
export function html(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
export function calc(entries=[],accounts=[],transfers=[]){const s={income:0,expense:0,balance:0,monthExpense:0,todayExpense:0,biggest:0};const now=new Date(),ym=todayISO(now).slice(0,7),td=todayISO(now);for(const e of entries){const n=Number(e.amount||0);if(e.type==='income')s.income+=n;else{s.expense+=n;if(String(e.entry_date||e.date).startsWith(ym))s.monthExpense+=n;if((e.entry_date||e.date)===td)s.todayExpense+=n;s.biggest=Math.max(s.biggest,n)}}s.balance=s.income-s.expense;const map=Object.fromEntries(accounts.map(a=>[a.id,{...a,balance:Number(a.opening_balance||a.openingBalance||0)}]));for(const e of entries){const id=e.account_id||e.accountId;if(map[id])map[id].balance+=e.type==='income'?Number(e.amount): -Number(e.amount)}for(const t of transfers){if(map[t.from_account_id])map[t.from_account_id].balance-=Number(t.amount);if(map[t.to_account_id])map[t.to_account_id].balance+=Number(t.amount)}return {stats:s,accounts:Object.values(map)}}
export function budgetState(settings={},monthExpense=0){const b=Number(settings.monthlyBudget||0),p=Number(settings.alertPercent||80);const left=b-monthExpense;const used=b?Math.round(monthExpense/b*100):0;const today=new Date();const days=new Date(today.getFullYear(),today.getMonth()+1,0).getDate()-today.getDate()+1;return {left,used,daily:b?Math.max(left/days,0):0,status:b&&used>=100?'danger':b&&used>=p?'warn':'safe'}}
export function byCategory(entries=[]){const m=new Map();for(const e of entries.filter(x=>x.type==='expense'))m.set(e.category,(m.get(e.category)||0)+Number(e.amount));return [...m.entries()].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value)}
export function trend7(entries=[]){return Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);const iso=todayISO(d);return {key:iso.slice(5),expense:entries.filter(e=>(e.entry_date||e.date)===iso&&e.type==='expense').reduce((a,b)=>a+Number(b.amount),0)}})}
